### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cybersecnn** [Pechnaya/Epidemic-Sound-Albums-Downloader#5]
Stings - Hip Hop & RnB [Stings]:
Levente Maneas - Tell Me What It’s Like (Sting)
Traceback (most recent call last):
  File "/home/epidemicsound/epidemic.py", line 89, in <module>
    trackAuthor = track['creatives']['mainArtists'][0]['name']
IndexError: list index out of range

**Comment by MikeSoftZP** [comment]
It's fixed in my PR: https://github.com/Pechnaya/Epidemic-Sound-Albums-Downloader/pull/4
And now merged.

**Comment by cybersecnn** [comment]
> Это исправлено в моем PR: #4 А теперь слито.

It all worked out. Thank you
